import { CentralReliefScheme } from "@/ai/schemas";

export const centralReliefSchemes: CentralReliefScheme[] = [
    {
      scheme_name: 'National Climate Crop Relief Mission',
      scheme_type: 'Direct Compensation',
      eligibility_land_min: 0,
      eligibility_land_max: 100,
      eligible_crop_types: ['All'],
      eligible_damage_types: ['Flood', 'Drought', 'Heatwave', 'Natural Calamity', 'Pest Attack'],
      applicable_states: 'All India',
      base_compensation_amount: 40000,
      subsidy_category: 'Disaster Relief',
      description: 'Provides direct financial relief to farmers who have suffered significant crop loss due to severe weather events like floods, drought, and heatwaves.',
      required_documents: ['Proof of Land Ownership', 'Damaged Crop Photograph', 'Aadhaar Card', 'Bank Account Details'],
      priority_group: 'All affected farmers',
      central_government_scheme: true,
    },
    {
      scheme_name: 'Central Small Farmer Income Stabilization Scheme',
      scheme_type: 'Income Support',
      eligibility_land_min: 0,
      eligibility_land_max: 2,
      eligible_crop_types: ['All'],
      eligible_damage_types: [],
      applicable_states: 'All India',
      base_compensation_amount: 12000,
      subsidy_category: 'Income Support',
      description: 'Provides guaranteed minimum income support to small and marginal farmers with less than 2 acres of land to ensure livelihood security during lean seasons or price volatility.',
      required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Bank Account Details', 'Income Certificate'],
      priority_group: 'Small & Marginal Farmers',
      central_government_scheme: true,
    },
    {
      scheme_name: 'National Crop Damage Compensation Fund',
      scheme_type: 'Direct Compensation',
      eligibility_land_min: 0,
      eligibility_land_max: 100,
      eligible_crop_types: ['All'],
      eligible_damage_types: ['Pest Attack', 'Hailstorm', 'Landslide', 'Unseasonal Rains'],
      applicable_states: 'All India',
      base_compensation_amount: 35000,
      subsidy_category: 'Disaster Relief',
      description: 'Offers direct monetary compensation based on the verified percentage of crop loss due to events like pest attacks, hailstorms, and unseasonal rains.',
      required_documents: ['Proof of Land Ownership', 'Damaged Crop Photograph', 'Aadhaar Card', 'Self-declaration of crop loss'],
      priority_group: 'All affected farmers',
      central_government_scheme: true,
    },
    {
      scheme_name: 'Smart Irrigation Modernization Subsidy',
      scheme_type: 'Equipment Subsidy',
      eligibility_land_min: 0,
      eligibility_land_max: 100,
      eligible_crop_types: ['All'],
      eligible_damage_types: [],
      applicable_states: 'All India',
      base_compensation_amount: 60000,
      subsidy_category: 'Infrastructure',
      description: 'Promotes water-use efficiency by providing subsidies for upgrading to drip and sprinkler irrigation systems, especially for farmers in water-scarce areas.',
      required_documents: ['Proof of Land Ownership', 'Quotation for equipment', 'Aadhaar Card'],
      priority_group: 'Farmers in water-stressed regions',
      central_government_scheme: true,
    },
    {
      scheme_name: 'National Rainfed Area Development Scheme',
      scheme_type: 'Holistic Support',
      eligibility_land_min: 0,
      eligibility_land_max: 100,
      eligible_crop_types: ['Millets', 'Pulses', 'Oilseeds'],
      eligible_damage_types: [],
      applicable_states: 'All India',
      base_compensation_amount: 25000,
      subsidy_category: 'Livelihood Support',
      description: 'Provides comprehensive support to farmers in rainfed areas through watershed development, soil conservation measures, and promotion of drought-resistant crops.',
      required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Proof of residence'],
      priority_group: 'Rainfed area farmers',
      central_government_scheme: true,
    },
    {
      scheme_name: 'Central High-Yield Seed Replacement Program',
      scheme_type: 'Input Subsidy',
      eligibility_land_min: 0,
      eligibility_land_max: 100,
      eligible_crop_types: ['Wheat', 'Rice', 'Maize', 'Soybean'],
      eligible_damage_types: [],
      applicable_states: 'All India',
      base_compensation_amount: 5000,
      subsidy_category: 'Productivity',
      description: 'Aims to boost crop productivity by providing certified high-yielding variety (HYV) seeds at subsidized rates.',
      required_documents: ['Aadhaar Card', 'Proof of Land Ownership'],
      priority_group: 'All farmers',
      central_government_scheme: true,
    },
    {
        scheme_name: 'Sustainable Organic Transition Incentive',
        scheme_type: 'Incentive',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 22000,
        subsidy_category: 'Sustainability',
        description: 'Offers financial support and technical guidance to farmers transitioning from conventional to organic farming over a three-year period.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Soil Health Card'],
        priority_group: 'Farmers willing to adopt organic practices',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Solar Pump Expansion Scheme',
        scheme_type: 'Equipment Subsidy',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 150000,
        subsidy_category: 'Infrastructure',
        description: 'A major push towards renewable energy in agriculture, providing up to 90% subsidy on the cost of installing solar-powered irrigation pumps.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Quotation for solar pump'],
        priority_group: 'All farmers, with priority to off-grid areas',
        central_government_scheme: true,
    },
    {
        scheme_name: 'National Farm Mechanization Upgrade Grant',
        scheme_type: 'Equipment Subsidy',
        eligibility_land_min: 2,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 125000,
        subsidy_category: 'Infrastructure',
        description: 'Provides assistance for purchasing modern agricultural equipment like tractors, rotavators, and harvesters to improve farm efficiency.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Equipment Quotation'],
        priority_group: 'Farmer Producer Organizations (FPOs)',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Women Farmer Empowerment Grant',
        scheme_type: 'Special Grant',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 30000,
        subsidy_category: 'Livelihood Support',
        description: 'A special financial assistance and skill development program exclusively for women who are landowners or are part of women-led Self-Help Groups.',
        required_documents: ['Proof of Land Ownership or SHG membership', 'Aadhaar Card', 'Bank Account Details'],
        priority_group: 'Women Farmers and SHGs',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Crop Diversification Incentive Program',
        scheme_type: 'Incentive',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 15000,
        subsidy_category: 'Productivity',
        description: 'Encourages farmers to shift from traditional monoculture (like wheat/rice) to higher-value crops such as horticulture, pulses, or oilseeds.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Proposal for new crop'],
        priority_group: 'All farmers in specified regions',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Disaster Emergency Crop Revival Package',
        scheme_type: 'Input Subsidy',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: ['Flood', 'Drought', 'Hailstorm', 'Pest Attack'],
        applicable_states: 'All India',
        base_compensation_amount: 8000,
        subsidy_category: 'Disaster Relief',
        description: 'Provides an immediate post-disaster kit of essential inputs like seeds and fertilizers to help farmers revive their fields for the next sowing season.',
        required_documents: ['Aadhaar Card', 'Proof of residence in disaster-affected area'],
        priority_group: 'Farmers in officially declared disaster areas',
        central_government_scheme: true,
    },
    {
        scheme_name: 'National Horticulture Expansion Subsidy',
        scheme_type: 'Holistic Support',
        eligibility_land_min: 0.5,
        eligibility_land_max: 10,
        eligible_crop_types: ['Mango', 'Banana', 'Tomato', 'Onion', 'Flowers'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 50000,
        subsidy_category: 'Productivity',
        description: 'A comprehensive scheme providing support for high-quality planting material, greenhouse construction, and post-harvest management for fruit and vegetable farmers.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Horticulture plan'],
        priority_group: 'Horticulture farmers',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Central Storage Infrastructure Support',
        scheme_type: 'Infrastructure',
        eligibility_land_min: 5,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 500000,
        subsidy_category: 'Infrastructure',
        description: 'Provides credit-linked back-ended subsidy for the construction of warehouses, silos, and cold storage units to reduce post-harvest losses.',
        required_documents: ['Detailed Project Report (DPR)', 'Proof of Land Ownership', 'Bank Loan Sanction Letter'],
        priority_group: 'FPOs and Agri-entrepreneurs',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Agri-Tech Adoption Subsidy',
        scheme_type: 'Technology Subsidy',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 20000,
        subsidy_category: 'Productivity',
        description: 'Provides subsidies for adopting modern farming technologies, including drone-based spraying, sensor-based irrigation, and farm management software.',
        required_documents: ['Aadhaar Card', 'Proof of Land Ownership', 'Quotation for technology service/product'],
        priority_group: 'Tech-savvy farmers and FPOs',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Youth Farmer Innovation Fund',
        scheme_type: 'Special Grant',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 100000,
        subsidy_category: 'Livelihood Support',
        description: 'A competitive grant for farmers under the age of 35 to support innovative projects in agriculture, from new farming techniques to value-added products.',
        required_documents: ['Detailed Project Proposal', 'Age Proof (under 35)', 'Aadhaar Card'],
        priority_group: 'Young Farmers',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Soil Health Restoration Grant',
        scheme_type: 'Input Subsidy',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 7500,
        subsidy_category: 'Sustainability',
        description: 'Based on the Soil Health Card recommendations, this grant provides financial assistance for purchasing micro-nutrients and soil amendments to restore soil fertility.',
        required_documents: ['Soil Health Card', 'Proof of Land Ownership', 'Aadhaar Card'],
        priority_group: 'Farmers with poor soil health',
        central_government_scheme: true,
    },
    {
        scheme_name: 'National Export Crop Promotion Incentive',
        scheme_type: 'Incentive',
        eligibility_land_min: 2,
        eligibility_land_max: 100,
        eligible_crop_types: ['Tea', 'Coffee', 'Spices', 'Mango', 'Grapes'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 80000,
        subsidy_category: 'Productivity',
        description: 'Provides support to meet international quality and packaging standards for farmers growing crops with high export potential.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Export Plan'],
        priority_group: 'Exporters and FPOs',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Crop Insurance Premium Relief Scheme',
        scheme_type: 'Insurance Support',
        eligibility_land_min: 0,
        eligibility_land_max: 5,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 4000,
        subsidy_category: 'Livelihood Support',
        description: 'Provides a subsidy on the premium for the Pradhan Mantri Fasal Bima Yojana (PMFBY) for small and medium farmers, making crop insurance more affordable.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Kisan Credit Card (KCC)'],
        priority_group: 'Small and Medium Farmers',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Livelihood Security Buffer Scheme',
        scheme_type: 'Income Support',
        eligibility_land_min: 0,
        eligibility_land_max: 2,
        eligible_crop_types: ['All'],
        eligible_damage_types: ['Drought', 'Flood'],
        applicable_states: 'All India',
        base_compensation_amount: 10000,
        subsidy_category: 'Disaster Relief',
        description: 'An emergency fund providing a one-time direct benefit transfer to small farmers in disaster-hit areas to help them sustain their livelihood.',
        required_documents: ['Aadhaar Card', 'Bank Account Details', 'Proof of residence in affected area'],
        priority_group: 'Small farmers in disaster-affected areas',
        central_government_scheme: true,
    },
    {
        scheme_name: 'National Water Efficiency Incentive',
        scheme_type: 'Incentive',
        eligibility_land_min: 0,
        eligibility_land_max: 100,
        eligible_crop_types: ['Millets', 'Pulses', 'Maize'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 9000,
        subsidy_category: 'Sustainability',
        description: 'A bonus subsidy provided to farmers who cultivate crops that have low water requirements, promoting water conservation in agriculture.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Proof of crop sown'],
        priority_group: 'Farmers in water-scarce zones',
        central_government_scheme: true,
    },
    {
        scheme_name: 'Marginal Farmer Stabilization Grant',
        scheme_type: 'Income Support',
        eligibility_land_min: 0,
        eligibility_land_max: 1,
        eligible_crop_types: ['All'],
        eligible_damage_types: [],
        applicable_states: 'All India',
        base_compensation_amount: 15000,
        subsidy_category: 'Livelihood Support',
        description: 'A dedicated financial support scheme for marginal farmers holding less than 1 acre of land, designed to stabilize their income.',
        required_documents: ['Proof of Land Ownership', 'Aadhaar Card', 'Bank Account Details'],
        priority_group: 'Marginal Farmers (<1 acre)',
        central_government_scheme: true,
    }
  ];
  